LMS/LMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('LMS-restricted-path/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("management_system/", include("management_system.urls")),
    path("", RedirectView.as_view(url="management_system/")),
    path("payments/", include("payments.urls")),
    path("api/", include("api.urls")),
    path("api/accounts/", include("api.accounts.urls")),
    path("api/management_system_api/", include("api.management_system.urls")),
    path("api_auth/", include("rest_framework.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LMS/accounts/urls.py
from django.urls import path

from .views import (sign_up,
                    sign_in,
                    MembersInboxView,
                    MembersBorrowedBooksView,
                    sign_out,
                    wallet_view,
                    books_calendar_view,
                    make_renewal_request,
                    forgot_password,
                    reset_password,
                    profile_page_view,
                    transaction_report_csv,
                    credit_wallet
                    )

app_name = "accounts"

urlpatterns = [
    path("sign-up/", sign_up, name="sign_up"),
    path("sign-in/", sign_in, name="sign_in"),
    path("sign-out/", sign_out, name="sign_out"),
    path("forgot_password", forgot_password, name="forgot_password"),
    path('reset_password/password-token/<str:uid>/<str:token>', reset_password, name='reset_password'),
    path("profile_page/", profile_page_view, name="profile_page"),

    path("inbox/", MembersInboxView.as_view(), name="member_inbox"),
    path("books/", MembersBorrowedBooksView.as_view(), name="books"),
    path("wallet/", wallet_view, name="member_wallet"),
    path("book_calendar/", books_calendar_view, name="books_calendar"),
    path("make_renewal_request/<int:pk>", make_renewal_request, name="make_renewal"),

    path("transaction_report/", transaction_report_csv, name='transaction_report'),
    path("credit_wallet/", credit_wallet, name="credit_wallet" )

]

LMS/api/management_system/urls.py
from django.urls import path

from .views import BookDetailView, BookListView, ManagementSystemApiRoot

app_name = "management_system_api"

urlpatterns = [
    path("", ManagementSystemApiRoot.as_view(), name="api_root"),
    path("book-list/", BookListView.as_view(), name="book_list"),
    path("book-detail/<int:pk>/", BookDetailView.as_view(), name="book_detail")

]

LMS/management_system/urls.py
from django.urls import path

from .views import (home,
                    add_book,
                    edit_book_details,
                    delete_book,
                    MakeBookRequestView,
                    LibrarianBookRequestView,
                    AcceptBookRequestView,
                    RejectBookRequestView,
                    pick_unpicked_books,
                    delete_unpicked_books,
                    MakeBookReturnsView,
                    approve_book_return,
                    reject_book_return,
                    ReportView,
                    ImportDataViaApiView,
                    suspend_unsuspend_member,
                    test_,
                    high_paying_customer_pdf,
                    popular_books_pdf,
                    RejectRenewalRequestView,
                    AcceptRenewalRequestView,
                    book_stock_report_csv,
                    popular_books_csv,
                    high_paying_customers_csv,
                    book_detail_view,
                    read_later_view,
                    MembersActionView,
                    send_warning_message
                    )

app_name = 'management_system'

urlpatterns = [
    path("", home, name="home"),
    path("add_book/", add_book, name="add_book"),
    path("book_details/<int:pk>", book_detail_view, name="book_detail"),
    path("read_later/<int:pk>", read_later_view, name="read_later"),
    path("edit_book_details/<int:pk>", edit_book_details, name="edit_book_details"),
    path("delete_book/<int:pk>", delete_book, name="delete_book"),

    path("make_book_request/<int:pk>", MakeBookRequestView.as_view(), name='book_request'),

    path("librarian_book_request/", LibrarianBookRequestView.as_view(), name="librarian_book_page"),
    path("accept_book_request/<int:pk>", AcceptBookRequestView.as_view(), name='accept_book_request'),
    path("reject_book_request/<int:pk>", RejectBookRequestView.as_view(), name='reject_book_request'),

    path("pick_unpicked_book/<int:pk>", pick_unpicked_books, name="pick_unpicked_books"),
    path("delete_unpicked_book/<int:pk>", delete_unpicked_books, name="delete_unpicked_books"),

    path("make_book_return/<int:pk>", MakeBookReturnsView.as_view(), name="make_book_return"),
    path("approve_book_return/<int:pk>", approve_book_return, name="approve_book_return"),
    path("reject_book_return/<int:pk>", reject_book_return, name="reject_book_return"),

    path("library_report/", ReportView.as_view(), name="library_report"),
    path("book_stock_report_csv/", book_stock_report_csv, name="book_stock_csv"),
    path("popular_books_csv/", popular_books_csv, name="popular_books_csv"),
    path("high_paying_customers_csv/", high_paying_customers_csv, name="high_paying_customers_csv"),


    path("import_books_via_api/", ImportDataViaApiView.as_view(), name="import_data"),
    path("suspend_member/<str:username>/", suspend_unsuspend_member, name="suspend_unsuspend_member"),
    path("send_warning_message/<int:id>/", send_warning_message, name="send_warning_message"),

    path("reject_renewal_request/<int:pk>", RejectRenewalRequestView.as_view(), name="reject_renewal"),
    path("accept_renewal_request/<int:pk>", AcceptRenewalRequestView.as_view(), name="accept_renewal"),

    path("403/", test_, name='test'),

    path("high_paying_customers_pdf/", high_paying_customer_pdf, name="high_paying_customers_pdf"),
    path("popular_books_pdf/", popular_books_pdf, name="popular_books_pdf"),
    path("member_page/", MembersActionView.as_view(), name="member_page")

]

LMS/management_system/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

from accounts.models import Members


# Create your models here.

class ActiveManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class InActiveManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().filter(is_active=False)


class ReturnedManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().filter(is_active=False, is_returned=True, is_picked=True)


class NotReturnedManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True, is_returned=False, is_picked=True)


class AnsweredManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().filter(is_answered=True)


class NotAnsweredManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().filter(is_answered=False)


class PickedManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().filter(is_picked=True)


class NotPickedManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().filter(is_picked=False)


class Genre(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name


class Book(models.Model):
    bookID = models.AutoField(primary_key=True, unique=True, editable=False)
    title = models.CharField(max_length=500, null=True)
    genre = models.ManyToManyField(Genre)
    authors = models.TextField(
        help_text="End Every Name with a \, e.g, Adekunle, Ciroma Chukwuma/ , the main author's name should be the "
                  "first")
    thumbnail = models.ImageField(blank=True, upload_to="book_thumbnail", default="book_default.png")
    description = models.TextField(blank=True, default="No Description Available !")
    isbn = models.CharField(max_length=10, null=True, blank=True)
    isbn13 = models.CharField(max_length=13)
    average_rating = models.DecimalField(null=True, default=0.0, decimal_places=2, max_digits=3,
                                         validators=[MinValueValidator(0.0)], blank=True)
    ratings_count = models.IntegerField(null=True, default=0, validators=[MinValueValidator(0)], blank=True)
    language_code = models.CharField(max_length=7, null=True, blank=True)
    num_of_pages = models.IntegerField(validators=[MinValueValidator(1)], null=True, blank=True)
    publisher = models.CharField(max_length=500, null=True, blank=True, default="No Publisher")
    publication_date = models.DateField(null=True, blank=True)
    quantity = models.IntegerField(default=1, validators=[MinValueValidator(1)], blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    objects = models.Manager()
    active_objects = ActiveManager()
    inactive_objects = InActiveManager()

    class Meta:
        verbose_name = "Book"
        verbose_name_plural = "Books"
        ordering = ("-bookID",)
        unique_together = ("title", 'isbn', 'isbn13')

    def __str__(self):
        return self.title

    def quantity_lent_out(self):
        return BorrowedBook.active_objects.filter(book_id=self.bookID, is_picked=True).count()

    def quantity_available(self):
        if int(self.quantity - BorrowedBook.not_returned_objects.filter(book_id=self.bookID).count()) < 0:
            return 0
        return int(self.quantity - BorrowedBook.not_returned_objects.filter(book_id=self.bookID).count())

    def times_borrowed(self):
        return BorrowedBook.objects.filter(book_id=self.bookID).count()


class BookRequest(models.Model):
    name = models.ForeignKey(Members, on_delete=models.SET_NULL, null=True)
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    date_requested = models.DateTimeField(auto_now_add=True)
    is_answered = models.BooleanField(default=False)

    objects = models.Manager()
    answered_objects = AnsweredManager()
    not_answered_objects = NotAnsweredManager()

    class Meta:
        ordering = ("-date_requested",)


class BorrowedBook(models.Model):
    borrower = models.ForeignKey(Members, on_delete=models.SET_NULL, null=True)
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    date_borrowed = models.DateTimeField(auto_now_add=True)
    date_to_be_returned = models.DateField(null=True)
    date_returned = models.DateField(null=True, blank=True)
    debt_incurred_default = models.DecimalField(null=True, blank=True, decimal_places=2,
                                                max_digits=5, default=0.00, )
    is_picked = models.BooleanField(default=False)
    is_returned = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = models.Manager()
    returned_objects = ReturnedManager()
    not_returned_objects = NotReturnedManager()
    active_objects = ActiveManager()
    inactive_objects = InActiveManager()

    def __str__(self):
        return self.book.title


class RenewalRequest(models.Model):
    borrowed_book = models.ForeignKey(BorrowedBook, on_delete=models.SET_NULL, null=True)
    renewal_days = models.IntegerField(null=True, validators=[MinValueValidator(0), MaxValueValidator(21)])
    new_date_of_return = models.DateField(null=True)
    date_applied = models.DateField(auto_now_add=True)
    is_approved = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = models.Manager()
    active_objects = ActiveManager()
    inactive_objects = InActiveManager()


class BookReturn(models.Model):
    borrowed_book = models.ForeignKey(BorrowedBook, on_delete=models.SET_NULL, null=True)
    is_approved = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = models.Manager()
    active_objects = ActiveManager()
    inactive_objects = InActiveManager()

    def __str__(self):
        return self.borrowed_book.book.title


class BookReview(models.Model):
    member = models.ForeignKey(Members, on_delete=models.SET_NULL, null=True)
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    message = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    objects = models.Manager()
    active_objects = ActiveManager()
    inactive_objects = InActiveManager()

    def __str__(self):
        return self.book.title


class ReadLater(models.Model):
    member = models.ForeignKey(Members, on_delete=models.SET_NULL, null=True)
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    objects = models.Manager()
    active_objects = ActiveManager()
    inactive_objects = InActiveManager()

LMS/management_system/forms.py
from django import forms

from .models import Book, BookReview


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        exclude = ("bookID", "date_added", "is_active")


class BookEditForm(forms.ModelForm):
    class Meta:
        model = Book
        exclude = ("is_active", "date_added")


class ImportDataViaApiForm(forms.Form):
    name = forms.CharField(max_length=500, help_text="Enter the name of the Api", required=True)
    number_of_books = forms.IntegerField(help_text="Enter the amount of books you want to import, not more than 30 "
                                                   "books", required=True)
    api_link = forms.CharField(max_length=500, help_text="Enter the link for the API", required=True)


class BookReviewForm(forms.ModelForm):
    class Meta:
        model = BookReview
        fields = ("message", )

LMS/api/management_system/views.py
from rest_framework.response import Response
from rest_framework.generics import RetrieveUpdateDestroyAPIView, ListCreateAPIView
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.reverse import reverse
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import SessionAuthentication, TokenAuthentication

from .serializers import BookSerializer
from .permissions import IsStaffOrReadOnly
from .mixins import IsStaffOrReadOnlyMixins
from management_system.models import Book


class ManagementSystemApiRoot(APIView):
    def get(self, request):
        return Response({
            "book": reverse("management_system_api:book_list", request=request),
        })


class BookListView(IsStaffOrReadOnlyMixins, ListCreateAPIView):
    queryset = Book.active_objects.all()
    serializer_class = BookSerializer
    authentication_classes = [SessionAuthentication, TokenAuthentication]


class BookDetailView(IsStaffOrReadOnlyMixins, RetrieveUpdateDestroyAPIView):
    queryset = Book.active_objects.all()
    serializer_class = BookSerializer

    def delete(self, request, *args, **kwargs):
        instance = self.get_object()
        instance.is_active = False
        instance.save()
        return Response(status=status.HTTP_204_NO_CONTENT)

LMS/templates/management_system/home.html
{% extends "base_generic.html" %}
{% load static %}

{% block title %}<title>Vilgax Library</title>{%  endblock  %}

{% block content %}
  <style>
  .home--grid{
    display: grid;
    grid-template-columns:0.5fr 3fr;
    background-color:white;
  }



  .books--grid--top--image{
    height: 333px;
    width: 1250px;
  }

  .books--grid h2{
    margin-left:10px;
    margin-top:70px;
  }


  .library--status{
    height: 70px;
    width: 400px;
    background-color:#FFFFFF;
    color:#1E5288;
    margin:-200px 00px 0px 0px;
    position: relative;

    z-index: 0;
    padding:5px;
  }

  .library--status h3{
    font-family: Sora;
    font-size: 20px;
    font-weight: 700;
    line-height: 48px;
    text-align: left;
    margin-top:-15px;
    margin-left: 30px;
  }

  .status_dud{
     height: 12px;
     width: 12px;
     margin-left: 30px;
     margin-top:-10px;
  }

  #create_book_image {
    height: 40px;
    width: 40px;
    margin-top: -90px;
    position:absolute;
    left:350px;



  }

  #create_book_image:hover {
    cursor:pointer;

  }

  .library--status p{
    font-family: Sora;
    font-size: 17px;
    font-weight: 400;
    line-height: 27px;
    font-family: Sora;
    text-align: left;
    {% if is_open %}
      color:#3D7500;
    {% else %}
      color:red;
    {% endif %}
    margin: -22px 0px 25px 48px;


  }


  .library--search--appointment{
      display:grid;
      grid-template-columns:2fr 1fr;
      margin:130px 0px;
  }

  .library--search{
      height:220px;
      background-color: #0C234B;


  }

  .library--search form{
      position:relative;

  }

  .library--search h3{
      height: 41px;
      width: 234px;
      font-family: Sora;
      font-size: 32px;
      font-weight: 600;
      line-height: 40px;
      letter-spacing: 0em;
      text-align: left;
      color:white;
      margin-left:25px;

  }

  .library--search input[type=text]{
      height: 60px;
      width: 800px;
      border-radius:8px;
      margin-top: 10px;
      margin-left:22px;
  }


   .library--search button{
      height:30px;
      float: right;
      margin: -40px 90px 0px 0px;
      background-color: #790417;
      color: #FFFFFF;
      padding:5px;
      border-radius:5px;
      z-index:1000;
      position: absolute;
      top: 68px;
      right: -40px;
      z-index: 1000;
      cursor:pointer;
  }


  .library--appointment{
      width: 387px;
      margin-left: 10px;
  }

  .working--hours{
    margin:5px;
    background-color:#E2E9EB;
    padding:10px;

  }

  .working--hours h3{
    height: 30px;
    width: 168px;
    font-family: Sora;
    font-size: 24px;
    font-weight: 600;
    line-height: 30px;
    text-align: left;
    color: #001C48;
  }

  .first--p{
    height: 20px;
    width: 116px;
    font-family: Sora;
    font-size: 16px;
    font-weight: 300;
    line-height: 15px;
    text-align: left;
    color:#001C48;
  }

  .second--p{
      height: 19px;
      width: 240px;
      font-family: Milo OT;
      font-size: 16px;
      font-weight: 400;
      line-height: 20px;
      text-align: left;
      color:#333333;
  }


  .library--appointment button{
    background-color:#790417;
    height: 30px;
    width: 180px;
    margin: 5px;
    color:white;
    border: 1px solid #790417;
  }

  .library--appointment span{
      font-family: Sora;
      font-size: 12px;
      font-weight: 400;
      line-height: 15px;
      text-align: left;
  }

  .super--books--container{
     display:grid;
     grid-template-columns:0.5fr 0.5fr 0.5fr 0.5fr 0.5fr;
     column-gap: 5px;
     row-gap:20px;
  }


  .book--container{
     height: 300px;
     width:215px;
     border-radius: 10px;
     padding:5px;
  }

  .book--container a:hover{
     cursor:pointer
  }


   .book--container img{
      height:200px;
      width:200px;
      padding:10px;
      border-radius:25px;
   }


   .book--container p{
      font-family: Sora;
      font-size: 17px;
      font-weight: 600;
      line-height: 30px;
      text-align: left;
      display: flex;
      justify-content:center;
      align-items:center;
      margin-top: 0px;
   }


   .book--container span{
        color:white;
   }

   .book--container button{
      margin-left:7px;
      margin-bottom:3px;
      background-color: #FD5252;
      height: 26px;
      width: 200px;
      border:1px solid #FD5252;
      border-radius:5px;
      cursor:pointer;
   }

</style>


  <div class="home--grid">

  {% include 'genre_component.html' %}

  <div class="books--grid">

    {% include 'navbar.html' %}

    <img src="{% static 'images/container.png' %}" alt="Vilgax Library"  class="books--grid--top--image">

    <div class="library--status">
      <h3>Vilgax Library</h3>
      {% if is_open %}
      <img src="{% static 'images/img_2.png' %}" alt="Now Open" class="status_dud">
      <p>Open Now</p>
      {% else %}
      <img src="{% static 'images/img_13.png' %}" alt="Currently Closed" class="status_dud">
      <p>Currently Closed</p>
      {% endif %}

        {% if request.user.is_authenticated and request.user.is_staff %}
        <a href="{% url 'management_system:add_book' %}"><img src="{% static 'images/img_12.png' %}" alt="create_book" id="create_book_image"></a>
        {% endif %}
    </div>

    <div class="library--search--appointment">
      <div class="library--search">

        <h3>Library Search</h3>

        <form action="" method="GET" >
        <input type="text" name="search" placeholder="Enter the author, title or genre">
          <button type="submit">Search</button>
          </form>


      </div>


      <div class="library--appointment">
        <div class="working--hours">
          <h3>Today's Hours</h3>

          <p class="first--p">Library access<span>{%if is_open %} currently open {% else %} Currently Closed {% endif %}</span></p>
          <p class="second--p">Opens at {{open_time}}, Closes at {{close_time}}</p>
        </div>

        <button type="submit" class="appointment--study-room"><span>Book a study room</span></button>
        <button type="submit" class="appointment--tutor"><span>Find a Tutor</span></button>

      </div>




    </div>




    <h2>Books available ({{books.count}}) </h2>

    <div class="super--books--container">
          {% for book in books %}
            {% if book.quantity_available > 0 %}
              <div class="book--container">
             <a href="{% url 'management_system:book_detail' book.bookID %}" >
            <img src="{{book.thumbnail.url}}" alt="{{book}}">
                  </a>
            <p>{{book.title|truncatechars:20}}</p>
<!--            <a href="{% url 'management_system:edit_book_details' book.bookID %}">Edit book</a>-->
<!--            <a href="{% url 'management_system:delete_book' book.bookID %}">Delete book</a>-->
            {% if request.user.is_authenticated %}
            {% if book.bookID not in members_book_request %}
                  <a href="{% url 'management_system:book_request' book.bookID %}"><button><span>Request Book</span></button></a>
                  {% else %}
                  <a href="{% url 'management_system:book_request' book.bookID %}"><button style="background-color:#AB0520;"><span>Requested</span></button></a>
            {% endif %}
                  {% endif %}
          </div>
            {% endif %}
          {% empty %}
              <div class="book--container">
            <p>No Book available at the moment</p>
          </div>
          {% endfor %}
    </div>


    <h2>Popular Books </h2>

    <div class="super--books--container">
          {% for book in popular_books %}
          <div class="book--container">
              <a href="{% url 'management_system:book_detail' book.bookID %}" >
            <img src="{{book.thumbnail.url}}" alt="{{book}}">
                  </a>
            <p>{{book.title|truncatechars:20}}</p>

<!--            <a href="{% url 'management_system:edit_book_details' book.bookID %}">Edit book</a>-->
<!--            <a href="{% url 'management_system:delete_book' book.bookID %}">Delete book</a>-->
            {% if request.user.is_authenticated %}
            {% if book.bookID not in members_book_request %}
              <a href="{% url 'management_system:book_request' book.bookID %}"><button><span>Request Book</span></button></a>
              {% else %}
              <a href="{% url 'management_system:book_request' book.bookID %}"><button style="background-color:#AB0520;"><span>Requested</span></button></a>
            {% endif %}
              {% endif %}
          </div>
          {% empty %}
          <div class="book--container">
            <p>No Book available at the moment</p>
          </div>
          {% endfor %}
    </div>

        {% include "footer.html" %}

  </div>




</div>

<!--<div class="create_book">-->

<!--    <h3>Create Book</h3>-->

<!--    <form action="{% url 'management_system:add_book' %}" method="POST">-->
<!--    {% csrf_token %}-->


<!--    <label>Title</label>-->
<!--    <br>-->
<!--    {{form.title}}-->
<!--    <br>-->
<!--    <br>-->

<!--    <label>Genre</label>-->
<!--    <br>-->
<!--    {{form.genre}}-->
<!--    <br>-->
<!--    <br>-->

<!--    <label>Authors</label>-->
<!--    <br>-->
<!--    {{form.authors}}-->
<!--    <br>-->
<!--    <br>-->

<!--    <label>Thumbnail</label>-->
<!--    <br>-->
<!--    {{form.thumbnail}}-->
<!--    <br>-->
<!--    <br>-->

<!--    <label>Descripton</label>-->
<!--    <br>-->
<!--    {{form.description}}-->
<!--    <br>-->
<!--    <br>-->

<!--    <label>ISBN13</label>-->
<!--    <br>-->
<!--    {{form.isbn13}}-->
<!--    <br>-->
<!--    <br>-->

<!--    <br>-->
<!--    <input type="submit" value="Create Book">-->
<!--</form>-->


<!--    <p id="create_book_home"><a href="{% url 'management_system:home' %}">-->
<!--        <img id='create_book_home_img' src="{% static 'images/img_1.png'%}" alt="Sign In">Back To HomePage</a></p>-->

<!--</div>-->


<!--<div class="import_api_data">-->

<!--  <h3>Import API Data</h3>-->

<!--    <form action="" method="POST" enctype="multipart/form-data">-->
<!--  {% csrf_token %}-->
<!--  <label>Name</label>-->
<!--  <br>-->
<!--  {{api_form.name}}-->
<!--  <br>-->
<!--  <br>-->

<!--  <label>Number Of Books</label>-->
<!--  <br>-->
<!--  {{api_form.number_of_books}}-->
<!--  <br>-->
<!--  <br>-->

<!--  <label>Api Link</label>-->
<!--  <br>-->
<!--  {{api_form.api_link}}-->
<!--  <br>-->
<!--  <br>-->


<!--  <input type="submit" value="Import">-->
<!--</form>-->

<!--    <p id="import_books"><a href="">-->
<!--        <img id='import_books_image_img' src="{% static 'images/img_1.png'%}" alt="Sign In">Back To HomePage</a></p>-->

<!--</div>-->

<script>

     document.querySelector("#create_book_image").addEventListener("click", function(){

        document.querySelector(".create_book").classList.add("active");

    });


    document.querySelector("#create_book_home_img").addEventListener("click", function(){

        document.querySelector(".create_book").classList.remove("active");

    });

    console.log("running")
     document.querySelector("#import_api_data_nav").addEventListener("click", function(){

        document.querySelector(".import_api_data").classList.remove("active");

    });
 console.log("running")
    document.querySelector("#import_books_image_img").addEventListener("click", function(){

        document.querySelector(".import_api_data").classList.remove("active");

    });



</script>
{% endblock %}

LMS/templates/management_system/librarian_book_request_page.html
{% extends "base_generic.html" %}

{% block content %}
<div>
  <h3>Book Request</h3>
  <ul>
    {% for book_request in book_requests %}
    <li>{{book_request.name.username}} wants to lend {{book_request.book}}</li>
    <a href="{% url 'management_system:accept_book_request' book_request.id %}">Accept</a>
    <a href="{% url 'management_system:reject_book_request' book_request.id %}">Reject</a>
    {% empty %}
    <li>No book request yet </li>
    {% endfor %}
  </ul>


  <h3>Unpicked books</h3>
  <ul>
    {% for unpicked_book in unpicked_books %}
    <li>{{unpicked_book.book.title}} by {{unpicked_book.borrower.username}}</li>
    <li><a href="{% url 'management_system:pick_unpicked_books' unpicked_book.id %}">Pick</a></li>
    <li><a href="{% url 'management_system:delete_unpicked_books' unpicked_book.id %}">Delete</a></li>
    {% empty %}
    <li>No unpicked book at the moment</li>
    {% endfor %}

  </ul>

  <h3>Book Return</h3>
  <ul>
    {% for book in book_returns %}
    <li>{{book}}</li>
    <a href="{% url 'management_system:approve_book_return' book.id %}">Approve</a>
    <a href="{% url 'management_system:reject_book_return' book.id %}">Reject</a>
    {% empty %}
    <li>No Book Returns Yet</li>
    {% endfor %}
  </ul>

  <h3>Members</h3>
  <ul>
    {% for member in all_members %}
    <li>{{member.username}}</li>
    <a href="{% url 'management_system:suspend_unsuspend_member' member.username %}">Suspend</a>
    {% empty %}
    <li>No Members Yet</li>
    {% endfor %}
  </ul>


  <h3>Renewal Request</h3>
  <ul>
    {% for renewal_request in renewal_requests %}
    <li>{{renewal_request.borrowed_book.borrower.username}} wants to extend the lending period of
      {{renewal_request.borrowed_book.book}} by {{renewal_request.renewal_days}} days,
      book to now be returned on {{renewal_request.new_date_of_return}}, formerly {{renewal_request.borrowed_book.date_to_be_returned}} </li>
    <a href="{% url 'management_system:accept_renewal' renewal_request.id %}">Accept</a>
     <a href="{% url 'management_system:reject_renewal' renewal_request.id %}">Reject</a>
    {% empty %}
    <li>No Renewal Request Yet</li>
    {% endfor %}
  </ul>

  <h3>Suspended Members</h3>
  <ul>
    {% for member in suspended_members %}
    <li>{{member.username}}</li>
    <a href="{% url 'management_system:suspend_unsuspend_member' member.username %}">Unsuspend</a>
    {% empty %}
    <li>No suspended members Yet</li>
    {% endfor %}
  </ul>

  <h3>Book Default(elasped 100 days)</h3>
  <ul>
    {% for member in bad_default_members %}
    <li>{{member.username}}</li>
    <a href="{% url 'management_system:suspend_unsuspend_member' member.username %}">Suspend</a>
    {% empty %}
    <li>No such members Yet</li>
    {% endfor %}
  </ul>


</div>
{% endblock %}