LMS/LMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('LMS-restricted-path/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("management_system/", include("management_system.urls")),
    path("", RedirectView.as_view(url="management_system/")),
    path("payments/", include("payments.urls")),
    path("api/", include("api.urls")),
    path("api/accounts/", include("api.accounts.urls")),
    path("api/management_system_api/", include("api.management_system.urls")),
    path("api_auth/", include("rest_framework.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LMS/accounts/urls.py
from django.urls import path

from .views import (sign_up,
                    sign_in,
                    MembersInboxView,
                    MembersBorrowedBooksView,
                    sign_out,
                    wallet_view,
                    books_calendar_view,
                    make_renewal_request,
                    forgot_password,
                    reset_password,
                    profile_page_view,
                    transaction_report_csv,
                    credit_wallet
                    )

app_name = "accounts"

urlpatterns = [
    path("sign-up/", sign_up, name="sign_up"),
    path("sign-in/", sign_in, name="sign_in"),
    path("sign-out/", sign_out, name="sign_out"),
    path("forgot_password", forgot_password, name="forgot_password"),
    path('reset_password/password-token/<str:uid>/<str:token>', reset_password, name='reset_password'),
    path("profile_page/", profile_page_view, name="profile_page"),

    path("inbox/", MembersInboxView.as_view(), name="member_inbox"),
    path("books/", MembersBorrowedBooksView.as_view(), name="books"),
    path("wallet/", wallet_view, name="member_wallet"),
    path("book_calendar/", books_calendar_view, name="books_calendar"),
    path("make_renewal_request/<int:pk>", make_renewal_request, name="make_renewal"),

    path("transaction_report/", transaction_report_csv, name='transaction_report'),
    path("credit_wallet/", credit_wallet, name="credit_wallet" )

]

LMS/api/accounts/urls.py
from django.urls import path

from .views import (MemberListCreateView, AccountsApiRoot,
                    WalletListCreateView
                    )


app_name = "accounts_api"

urlpatterns = [
    path("", AccountsApiRoot.as_view(), name="accounts_root"),
    path("members", MemberListCreateView.as_view(), name="members_list_create"),


    path("wallet", WalletListCreateView.as_view(), name="wallet_list_create")
]

LMS/management_system/urls.py
from django.urls import path

from .views import (home,
                    add_book,
                    edit_book_details,
                    delete_book,
                    MakeBookRequestView,
                    LibrarianBookRequestView,
                    AcceptBookRequestView,
                    RejectBookRequestView,
                    pick_unpicked_books,
                    delete_unpicked_books,
                    MakeBookReturnsView,
                    approve_book_return,
                    reject_book_return,
                    ReportView,
                    ImportDataViaApiView,
                    suspend_unsuspend_member,
                    test_,
                    high_paying_customer_pdf,
                    popular_books_pdf,
                    RejectRenewalRequestView,
                    AcceptRenewalRequestView,
                    book_stock_report_csv,
                    popular_books_csv,
                    high_paying_customers_csv,
                    book_detail_view,
                    read_later_view,
                    MembersActionView,
                    send_warning_message
                    )

app_name = 'management_system'

urlpatterns = [
    path("", home, name="home"),
    path("add_book/", add_book, name="add_book"),
    path("book_details/<int:pk>", book_detail_view, name="book_detail"),
    path("read_later/<int:pk>", read_later_view, name="read_later"),
    path("edit_book_details/<int:pk>", edit_book_details, name="edit_book_details"),
    path("delete_book/<int:pk>", delete_book, name="delete_book"),

    path("make_book_request/<int:pk>", MakeBookRequestView.as_view(), name='book_request'),

    path("librarian_book_request/", LibrarianBookRequestView.as_view(), name="librarian_book_page"),
    path("accept_book_request/<int:pk>", AcceptBookRequestView.as_view(), name='accept_book_request'),
    path("reject_book_request/<int:pk>", RejectBookRequestView.as_view(), name='reject_book_request'),

    path("pick_unpicked_book/<int:pk>", pick_unpicked_books, name="pick_unpicked_books"),
    path("delete_unpicked_book/<int:pk>", delete_unpicked_books, name="delete_unpicked_books"),

    path("make_book_return/<int:pk>", MakeBookReturnsView.as_view(), name="make_book_return"),
    path("approve_book_return/<int:pk>", approve_book_return, name="approve_book_return"),
    path("reject_book_return/<int:pk>", reject_book_return, name="reject_book_return"),

    path("library_report/", ReportView.as_view(), name="library_report"),
    path("book_stock_report_csv/", book_stock_report_csv, name="book_stock_csv"),
    path("popular_books_csv/", popular_books_csv, name="popular_books_csv"),
    path("high_paying_customers_csv/", high_paying_customers_csv, name="high_paying_customers_csv"),


    path("import_books_via_api/", ImportDataViaApiView.as_view(), name="import_data"),
    path("suspend_member/<str:username>/", suspend_unsuspend_member, name="suspend_unsuspend_member"),
    path("send_warning_message/<int:id>/", send_warning_message, name="send_warning_message"),

    path("reject_renewal_request/<int:pk>", RejectRenewalRequestView.as_view(), name="reject_renewal"),
    path("accept_renewal_request/<int:pk>", AcceptRenewalRequestView.as_view(), name="accept_renewal"),

    path("403/", test_, name='test'),

    path("high_paying_customers_pdf/", high_paying_customer_pdf, name="high_paying_customers_pdf"),
    path("popular_books_pdf/", popular_books_pdf, name="popular_books_pdf"),
    path("member_page/", MembersActionView.as_view(), name="member_page")

]

LMS/accounts/views.py
import datetime
import csv

from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseForbidden
from django.contrib import messages
from django.conf.urls.static import settings
from django.contrib.auth import update_session_auth_hash, login, logout, authenticate
from django.views.generic import ListView, View
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import CustomMembersCreationForm, WalletPinForm, RenewalRequestForm, CustomMembersChangeForm
from .models import Members, Inbox, Wallet, WalletTransaction
from management_system.models import BorrowedBook, BookReturn, RenewalRequest, BookRequest


# Create your views here.

def not_staff(request, pk):
    user = Members.active_objects.get(id=pk)
    if not user.is_staff:
        messages.error(request, "You are not allowed")
        return HttpResponseForbidden


def sign_up(request):
    if request.method == "POST":
        form = CustomMembersCreationForm(request.POST, request.FILES)

        if form.is_valid():
            member = form.save(commit=False)
            member.email = member.email.lower()
            member.username = member.username.title()
            member.save()

            print(form.cleaned_data["email"])

            member_wallet = Wallet.objects.create(
                owner=Members.active_objects.get(email=form.cleaned_data["email"])

            )

            member_wallet.save()

            member_message = Inbox.objects.create(
                receiver=Members.active_objects.get(email=form.cleaned_data["email"]),
                sender="The Librarian",
                message=f"Welcome to Vilgax Library, A wallet has been created for you, Your wallet number is"
                        f"  {member_wallet.wallet_number} and your pin is {member_wallet.pin}....Once again, Welcome"

            )

            member_message.save()
            messages.success(request, f"welcome, {request.POST['username']}, You need to sign in")
            return HttpResponseRedirect(reverse("accounts:sign_in"))
        error = (form.errors.as_text()).split("*")
        messages.error(request, error[len(error) - 1])
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

    context = {
        "form": CustomMembersCreationForm(),
        "form_type": "SIGN UP"
    }

    return render(request, "accounts/sign_in_sign_up.html", context)


def sign_in(request):
    if request.method == "POST":
        email = request.POST["email_signin"].lower()
        password = request.POST["password_signin"]

        try:
            member = Members.objects.get(email=email)
        except Members.DoesNotExist as e:
            messages.error(request, "Member does not exist")
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

        member = authenticate(email=email, password=password)

        if member is not None:
            login(request, member)
            messages.success(request, f"welcome {member.username}")
            return HttpResponseRedirect(reverse("management_system:home"))
        messages.error(request, "Invalid Password !")
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
    logout(request)
    return render(request, "accounts/sign_in.html", {"form": CustomMembersCreationForm()})


def sign_out(request):
    logout(request)
    return HttpResponseRedirect(reverse("management_system:home"))


def forgot_password(request):
    if request.method == "POST":
        try:
            email = request.POST.get("email")
            user = Members.active_objects.get(email=email)
            uid = urlsafe_base64_encode(force_bytes(user.id))
            token = default_token_generator.make_token(user)
            current_site = get_current_site(request)

            email_body = {
                'token': token,
                "subject": "Recover Password",
                'message': f"Hi, {user.username} , kindly reset your password by clicking "
                           f"the following link . http://{current_site}/accounts/reset_password/password-token/{uid}/{token} "
                           f"to change your password",
                "recepient": email,
            }

            send_mail(
                email_body["subject"],
                email_body["message"],
                settings.EMAIL_HOST_USER,
                [email]

            )
            print(email_body["message"])
            messages.success(request, "A password reset mail has been sent to your mail")
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
        except Members.DoesNotExist or Exception as e:
            print(e)
            messages.error(request, "Member does not exist")
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

    return render(request, "accounts/forgot_password.html")


def reset_password(request, uid, token):
    if request.method == "POST":
        try:
            id_decode = urlsafe_base64_decode(uid)
            user = Members.active_objects.get(id=id_decode)

            if default_token_generator.check_token(user, token):
                password = request.POST.get("password1")
                confirm_password = request.POST.get("password2")

                if password == confirm_password:
                    user.set_password(password)
                    user.save()
                    messages.success(request, "password Recovered successfully")
                    return HttpResponseRedirect(reverse("main_store:index"))
                messages.error(request, "incorrect passwords")
                return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

            else:
                messages.error(request, "Invalid Token")
                return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
        except:
            messages.error(request, "Invalid link")
            return HttpResponseRedirect("accounts:sign_in")

    context = {
        "uid": urlsafe_base64_decode(uid),
        "token": Members.active_objects.get(id=urlsafe_base64_decode(uid)),

    }
    return render(request, "accounts/reset_password.html", context)


class MembersInboxView(LoginRequiredMixin, ListView):
    model = Inbox
    context_object_name = "members_messages"
    template_name = "accounts/inbox.html"
    login_url = "accounts:sign_in"

    def get_queryset(self):
        return Inbox.objects.filter(receiver_id=self.request.user.id)


class MembersBorrowedBooksView(LoginRequiredMixin, ListView):
    login_url = "accounts:sign_in"
    model = BorrowedBook
    template_name = "book_properties_page.html"

    def get_queryset(self):
        return BookRequest.not_answered_objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super(MembersBorrowedBooksView, self).get_context_data(*args, **kwargs)
        bad_default_books = BorrowedBook.not_returned_objects.filter(debt_incurred_default__gte=500).values_list(
            'borrower_id')

        # context["bad_default_members"] = Members.active_objects.filter(pk__in=bad_default_books)
        context["book_requests"] = self.get_queryset()
        context["unpicked_books"] = BorrowedBook.active_objects.filter(is_picked=False, is_returned=False)
        context["book_returns"] = BookReturn.active_objects.all()
        context["all_members"] = Members.active_objects.all()
        context["suspended_members"] = Members.inactive_objects.all()
        context["renewal_requests"] = RenewalRequest.active_objects.all()
        context["borrowed_books"] = BorrowedBook.not_returned_objects.filter(borrower_id=self.request.user.id)
        context["user_unpicked_books"] = BorrowedBook.objects.filter(borrower_id=self.request.user.id,
                                                                     is_returned=False,
                                                                     is_active=True, is_picked=False).order_by(
            'date_borrowed')
        context["default_books"] = BorrowedBook.not_returned_objects.filter(borrower_id=self.request.user.id,
                                                                            is_picked=True,
                                                                            date_to_be_returned__lte=datetime.datetime.today().date())
        return context


@login_required(login_url="accounts:sign_in")
def wallet_view(request):
    try:
        wallet = Wallet.objects.get(owner_id=request.user.id)
    except Wallet.DoesNotExist:
        messages.error(request, "Wallet Does Not Exist")
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

    if request.method == "POST":

        if int(request.POST.get("pin")) != wallet.pin:
            messages.error(request, "Invalid Pin")
            return HttpResponseRedirect(reverse("management_system:home"))
        messages.success(request, "It is working")
        return HttpResponseRedirect(reverse("management_system:home"))

    return render(request, "accounts/members_wallet.html", {"form": WalletPinForm()})


@login_required(login_url="accounts:sign_in")
def books_calendar_view(request):
    not_returned_books = BorrowedBook.not_returned_objects.filter(borrower_id=request.user.id)
    return render(request, "accounts/members_book_calendar.html", {"not_returned_books": not_returned_books})


@login_required(login_url="accounts:sign_in")
def make_renewal_request(request, pk):
    try:
        borrowed_book = BorrowedBook.not_returned_objects.get(id=pk, is_returned=False)
    except BorrowedBook.DoesNotExist:

LMS/api/accounts/views.py
from rest_framework.generics import ListCreateAPIView
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import SessionAuthentication

from .serializers import MembersSerializer, WalletSerializer
from accounts.models import Members, Wallet
from ..management_system.mixins import IsStaffOrReadOnlyMixins


class AccountsApiRoot(APIView):
    def get(self, request, *args, **kwargs):
        return Response({
            "members": reverse("accounts_api:members_list_create", request=request),
            "wallet": reverse("accounts_api:wallet_list_create", request=request)
        })


class MemberListCreateView(IsStaffOrReadOnlyMixins, ListCreateAPIView):
    serializer_class = MembersSerializer
    queryset = Members.active_objects.all()


class WalletListCreateView(IsStaffOrReadOnlyMixins, ListCreateAPIView):
    serializer_class = WalletSerializer
    queryset = Wallet.objects.all()

LMS/templates/accounts/borrowed_books.html
{% extends "base_generic.html" %}

{% block content %}
<h3>Unpicked Books</h3>
<ul>
    {% for unpicked_book in unpicked_books %}
    <li>{{unpicked_book}}</li>
    {% empty %}
    <li>I'm Empty</li>
    {% endfor %}
</ul>
<br>
<br>

<h3>Borrowed Books</h3>
<ul>
    {% for borrowed_book in borrowed_books %}
    <li>{{borrowed_book | title}} due on {{borrowed_book.date_to_be_returned}}</li>
    <a href="{% url 'management_system:make_book_return' borrowed_book.id %}">Make Book Return</a>
    <a href="{% url 'accounts:make_renewal' borrowed_book.id %}">Make Renewal</a>
    {% empty %}
    <li>I'm Empty</li>
    {% endfor %}
</ul>

<h3>Default Books</h3>
{% endblock %}

LMS/templates/accounts/inbox.html
{% extends "base_generic.html" %}

{% block content %}
<ul>
  {% for member_message in members_messages %}
  <li>{{member_message.sender}}</li>
  <li>{{member_message.message}}</li>
  {% empty %}
  <li><p>I'm Empty</p></li>
  {% endfor %}
</ul>
{% endblock %}

LMS/templates/accounts/members_book_calendar.html
{% extends 'base_generic.html' %}
{% load static %}
{% block content %}

<html>
  <head>
    <meta charset='utf-8' />
    <link href='{% static "scripts/fullcalendar/lib/main.css" %}' rel='stylesheet' />
    <script src='{% static "scripts/fullcalendar/lib/main.js" %}'></script>
    <script>

      document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');

        var calendar = new FullCalendar.Calendar(calendarEl, {
          initialView: 'dayGridMonth',
          timeZone:'Africa/Lagos',
          locale:'en',
          firstDay:1,
          events: [
          {% for book in not_returned_books %}
            {
              title: '{{ book.book }}',
              start: '{{ book.date_borrowed.isoformat }}',
              end:'{{ book.date_to_be_returned.isoformat }}',
            },
          {% endfor %}
          ]

        });

        calendar.render();
      });

    </script>
  </head>


  <body>
<!--  {%for event in group_events%}-->
<!--  <h4>{{event.time_start}}</h4>-->
<!--  {%endfor%}-->
    <div id='calendar'></div>
  </body>

</html>
{% endblock %}

LMS/templates/accounts/sign_in.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}

<style>
    .sign_in{
        display:grid;
        grid-template-columns:2fr 3fr;
        background-color: #f5f5f5
    }

    .sign_in_background_picture{
        width:720px;
        height:1000px;
    }

    .sign_in_form{
        display:flex;
        justify-content:center;
        align-items:center;
    }

    .sign_in_form h3{
        color:#54565B;
        font-family:mullish;
        font-weight:700;
        font-size:30px;
        line-height-25px;
    }

    .sign_in_form label{
        font-family:mullish;
        margin-bottom:80px;
        color:#54565B;

    }

    .sign_in_form input[type=email]{
        height: 5px;
        width: 300px;
        border-radius: 10px;
        padding: 22px 20px 22px 20px;
        background-color: #F9FAFB;
        margin: 15px 0px 30px 0px
    }

    .sign_in_form input[type=password]{
        height: 5px;
        width: 300px;
        border-radius: 10px;
        padding: 22px 20px 22px 20px;
        background-color: #F9FAFB;
        margin: 15px 0px 30px 0px
    }

    #password--eye{
        margin-left:-40px;
    }

     .sign_in_form input[type=checkbox]{
      height: 15px;
      width: 15px;
      border-radius: 2.5px;
      margin-top:-5px;

    }

    .sign_in_form span{
        color:#54565B;
        font-family:mullish;
    }

    #forgot--password{
        color: #2A639C;
        font-family:mullish;
        margin-left:100px;
        cursor:pointer;
    }



    .sign_in_form button{
        height: 5px;
        width: 350px;
        border-radius: 10px;
        padding: 22px 20px 22px 20px;
        background-color: #2A639C;
        margin: 5px 0px 15px 0px
    }

    .sign_in_form button:hover{
        cursor:pointer;
    }

    #sign-in-button-span{
        color:white;
        font-family:mullish;
        font-weight:700;
        font-size:15px;
    }

    .sign_in_form a{
      text-decoration:none;
      font-weight:400;
      font-size:15px;
      line-height:36.78px;
      color: #2A639C;
      font-family:mullish;
    }

    #create_account{
      color:#54565B;
      font-weight:400;
      font-size:15px;
      line-height:36.78px;
      display:flex;
      align-items:center;
      justify-content:center;
      cursor:pointer;
    }

    .pop--up--sign--up{
        height:700px;
        position:absolute;
        top:-150%;
        left:50%;
        opacity:0;
        transform:translate(-50%, -50%) scale(1.25);
        width:400px;
        padding:20px, 30px;
        background-color:white;
        box-shadow:2px 2px 5px 5px rgba(0,0,0,0.15);
        border-radius:10px;
        transition: top 0ms ease-in-out 0ms,
                    opacity 200ms ease-in-out 0ms,
                    transform 0ms ease-in-out 00ms;
    }

    .pop--up--sign--up.active{
        top:50%;
        opacity:1;
        transform:translate(-50%, -50%) scale(1);
        transition: top 0ms ease-in-out 200ms,
                    opacity 200ms ease-in-out 0ms,
                    transform 0ms ease-in-out 00ms;

    }

    .close-btn{
        position:absolute;
        top:10px;
        right:15px;
        width:25px;
        height:25px;
        background-color:#888;
        color:#eee;
        cursor:pointer;
        text-align:center;
        border-radius:15px;
        line-height:15px;

     }

    .pop--up--sign--up img{
        height: 80px;
        width: 150px;
        margin-left: 90px;
        margin-top: 20px;
    }


    .pop--up--sign--up h3{
        height: 35px;
        width: 229px;
        font-family: Mulish;
        font-size: 20px;
        font-weight: 700;
        line-height: 29px;
        text-align: center;
        color:#54565B;
        margin: -10px 0px 0px 50px
    }


     .pop--up--sign--up p{
        font-family: Mulish;
        font-size: 16px;
        font-weight: 400;
        line-height: 29px;
        text-align: center;
        color:#9FA19C;
    }


    #p--term--2{
        margin-top:-15px;
    }


    .sign-up--form{
       margin:15px;

    }

    .sign-up--form label{
       margin-left:20px;
    }

     .sign-up--form input[type=tel],
      .sign-up--form select,
      .sign-up--form input[type=email],
      .sign-up--form input[type=password],
      .sign-up--form input[type=text]{
        border:1px solid #2A639C;
        height: 30px;
        width: 300px;
        border-radius: 15px;
        margin-top:5px;
        margin-left:20px;

    }



    .sign-up--form input[type=submit]{
        border:1px solid #2A639C;
        background:#2A639C;
        margin-top:5px;
        height: 38px;
        width: 330px;
        border-radius: 8px;
        color:white;
        margin-left:20px;


    }

    #signup-paragraph{
       text-decoration:none;
       margin-left:-100px;
       margin-top:-15px;

    }

     .pop--up--sign--up a{
       text-decoration:none;
       margin-top:-5px;
    }


    #back-to-signin{
        height: 13px;
        width: 6px;
        margin-right:10px;

    }




     .pop--up--forgot--password{
        height:480px;
        position:absolute;
        top:-150%;
        left:50%;
        opacity:0;
        transform:translate(-50%, -50%) scale(1.25);
        width:500px;
        padding:20px, 30px;
        background-color:white;
        box-shadow:2px 2px 5px 5px rgba(0,0,0,0.15);
        border-radius:10px;
        transition: top 0ms ease-in-out 0ms,
                    opacity 200ms ease-in-out 0ms,
                    transform 0ms ease-in-out 00ms;
    }

    .pop--up--forgot--password.active{
        top:50%;
        opacity:1;
        transform:translate(-50%, -50%) scale(1);
        transition: top 0ms ease-in-out 200ms,
                    opacity 200ms ease-in-out 0ms,
                    transform 0ms ease-in-out 00ms;

    }



    .pop--up--forgot--password img{
        height: 80px;
        width: 150px;
        margin-left: 130px;
        margin-top: 20px;
    }


    .pop--up--forgot--password h3{
        height: 35px;
        width: 229px;
        font-family: Mulish;
        font-size: 20px;
        font-weight: 700;
        line-height: 29px;
        text-align: center;
        color:#54565B;
        margin: -10px 0px 0px 100px
    }


     .pop--up--forgot--password p{
        font-family: Mulish;
        font-size: 16px;
        font-weight: 400;
        line-height: 29px;
        text-align: center;
        color:#9FA19C;
    }

    #f-p-p-p--term--2{
        margin-top:-15px;
        margin-bottom:20px;
    }



    .forgot-password--form{
       margin:15px;

    }

    .forgot-password--form label{
       margin-top:20px;
       margin-left:160px;
       margin-bottom:17px;
    }


    .forgot-password--form span{
        font-size:16px;

    }


     .forgot-password--form input[type=email]{
        border:1px solid #2A639C;
        height: 40px;
        width: 300px;
        border-radius: 15px;
        margin-top:5px;
        margin-left:70px;

    }



    .forgot-password--form input[type=submit]{
        border:1px solid #2A639C;
        background:#2A639C;
        margin-top:5px;
        height: 38px;
        width: 330px;
        border-radius: 8px;
        color:white;
        margin-left:60px;
        cursor:pointer;


    }

    #f-p-signup-paragraph{
       text-decoration:none;
       margin-left:-140px;
       margin-top:-5px;

    }

     .pop--up--forgot--password a{
       text-decoration:none;
       margin-top:-5px;
    }


    #f-p-back-to-signin{
        height: 13px;
        width: 6px;
        margin-right:10px;
        margin-bottom: -1px;

    }











</style>

<div class="sign_in">

        <img src="{% static 'images/Group 342.png'%}" alt="Vilgax Library Signin page" class="sign_in_background_picture">


    <div class="sign_in_form">

       <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <h3>Sign In</h3>

                <label>Email </label>
                <br>
                <input type="email" name="email_signin" placeholder="Enter your email">
                <br>

                <label>Password </label>
                <br>
                <input type="password" name="password_signin" placeholder="Enter Password">
                <i class="fa fa-eye" style="font-size:15px" id="password--eye"></i>
                <br>

                <input type="checkbox"><span class="remember--me">Remember Me</span>
                <span id="forgot--password">Forgot Password ?</span>

                <br>
                <br>
                <button><span id="sign-in-button-span">Sign In</span></button>

                <br>
<!--                <p><a href="{% url 'accounts:sign_up' %}" id="create_account">Create an account</a></p>-->
                    <p id="create_account">Create an account</p>
            </form>
        </div>
</div>


<div class="pop--up--sign--up">
    <img src="{% static 'images/v logo.png'%}" alt="Vilgax Library Sign Up Form">
    <div class="sign-up--form">
<!--        <div class="close-btn">&times;</div>-->
        <form action="{% url 'accounts:sign_up' %}" method="POST" enctype="multipart/form-data">

            <h3>Create Account</h3>
                    <p id="p--term-1">By signing up in Vilgax Library,</p>
                <p id="p--term--2">you hereby agree to the terms and condition</p>
            {% csrf_token %}
            <label>Email</label>
            <br>
            {{form.email}}
            <br>
            <br>

            <label>Username</label>
            <br>
            {{form.username}}
            <br>
            <br>

<!--            <label>Phone Number</label>-->
<!--            <br>-->
<!--            {{form.phone_number}}-->
<!--            <br>-->
<!--            <br>-->

            <label>Gender</label>
            <br>
            {{form.gender}}
            <br>
            <br>

            <label>Password</label>
            <br>
            {{form.password1}}
            <br>
            <br>

            <label>Password Confirmation</label>
            <br>
            {{form.password2}}
            <br>
            <br>

            <input type="submit" value="Sign Up">
        </form>
    </div>

    <p id="signup-paragraph"><a href="{% url 'accounts:sign_in' %}"><img id='back-to-signin' src="{% static 'images/img_1.png'%}" alt="Sign In">Back To Sign In</a></p>
</div>


<div class="pop--up--forgot--password">
    <img src="{% static 'images/v logo.png'%}" alt="Vilgax Library Sign Up Form">
    <div class="forgot-password--form">
        <form action="{% url 'accounts:forgot_password' %}" method="POST" enctype="multipart/form-data" >
            {% csrf_token %}

              <h3>Forgot Password</h3>
            <p id="f-p-p--term-1">Enter your email below,</p>
            <p id="f-p-p--term--2">We will send instructions for setting a new Password</p>

            <br>
            <label><span>Registered Email</span></label>
            <br>
            <br>
            <input type="email" name="email" placeholder="Enter a registered email">
            <br>
            <br>

            <input type="submit" value="Submit">


        </form>
        </div>
    <p id="f-p-signup-paragraph"><a href="{% url 'accounts:sign_in' %}">
        <img id='f-p-back-to-signin' src="{% static 'images/img_1.png'%}" alt="Sign In">Back To Sign In</a></p>

</div>



<script>
    document.querySelector("#create_account").addEventListener("click", function(){

        document.querySelector(".pop--up--sign--up").classList.add("active");

    });

    document.querySelector("#back-to-signin").addEventListener("click", function(){

        document.querySelector(".pop--up--sign--up").classList.remove("active");

    });




    document.querySelector("#forgot--password").addEventListener("click", function(){

        document.querySelector(".pop--up--forgot--password").classList.add("active");

    });

    document.querySelector("#back-to-signin").addEventListener("click", function(){

        document.querySelector(".pop--up--sign--up").classList.remove("active");

    });

</script>
{% endblock %}