LMS/LMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('LMS-restricted-path/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("management_system/", include("management_system.urls")),
    path("", RedirectView.as_view(url="management_system/")),
    path("payments/", include("payments.urls")),
    path("api/", include("api.urls")),
    path("api/accounts/", include("api.accounts.urls")),
    path("api/management_system_api/", include("api.management_system.urls")),
    path("api_auth/", include("rest_framework.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LMS/accounts/urls.py
from django.urls import path

from .views import (sign_up,
                    sign_in,
                    MembersInboxView,
                    MembersBorrowedBooksView,
                    sign_out,
                    wallet_view,
                    books_calendar_view,
                    make_renewal_request,
                    forgot_password,
                    reset_password,
                    profile_page_view,
                    transaction_report_csv,
                    credit_wallet
                    )

app_name = "accounts"

urlpatterns = [
    path("sign-up/", sign_up, name="sign_up"),
    path("sign-in/", sign_in, name="sign_in"),
    path("sign-out/", sign_out, name="sign_out"),
    path("forgot_password", forgot_password, name="forgot_password"),
    path('reset_password/password-token/<str:uid>/<str:token>', reset_password, name='reset_password'),
    path("profile_page/", profile_page_view, name="profile_page"),

    path("inbox/", MembersInboxView.as_view(), name="member_inbox"),
    path("books/", MembersBorrowedBooksView.as_view(), name="books"),
    path("wallet/", wallet_view, name="member_wallet"),
    path("book_calendar/", books_calendar_view, name="books_calendar"),
    path("make_renewal_request/<int:pk>", make_renewal_request, name="make_renewal"),

    path("transaction_report/", transaction_report_csv, name='transaction_report'),
    path("credit_wallet/", credit_wallet, name="credit_wallet" )

]

LMS/management_system/urls.py
from django.urls import path

from .views import (home,
                    add_book,
                    edit_book_details,
                    delete_book,
                    MakeBookRequestView,
                    LibrarianBookRequestView,
                    AcceptBookRequestView,
                    RejectBookRequestView,
                    pick_unpicked_books,
                    delete_unpicked_books,
                    MakeBookReturnsView,
                    approve_book_return,
                    reject_book_return,
                    ReportView,
                    ImportDataViaApiView,
                    suspend_unsuspend_member,
                    test_,
                    high_paying_customer_pdf,
                    popular_books_pdf,
                    RejectRenewalRequestView,
                    AcceptRenewalRequestView,
                    book_stock_report_csv,
                    popular_books_csv,
                    high_paying_customers_csv,
                    book_detail_view,
                    read_later_view,
                    MembersActionView,
                    send_warning_message
                    )

app_name = 'management_system'

urlpatterns = [
    path("", home, name="home"),
    path("add_book/", add_book, name="add_book"),
    path("book_details/<int:pk>", book_detail_view, name="book_detail"),
    path("read_later/<int:pk>", read_later_view, name="read_later"),
    path("edit_book_details/<int:pk>", edit_book_details, name="edit_book_details"),
    path("delete_book/<int:pk>", delete_book, name="delete_book"),

    path("make_book_request/<int:pk>", MakeBookRequestView.as_view(), name='book_request'),

    path("librarian_book_request/", LibrarianBookRequestView.as_view(), name="librarian_book_page"),
    path("accept_book_request/<int:pk>", AcceptBookRequestView.as_view(), name='accept_book_request'),
    path("reject_book_request/<int:pk>", RejectBookRequestView.as_view(), name='reject_book_request'),

    path("pick_unpicked_book/<int:pk>", pick_unpicked_books, name="pick_unpicked_books"),
    path("delete_unpicked_book/<int:pk>", delete_unpicked_books, name="delete_unpicked_books"),

    path("make_book_return/<int:pk>", MakeBookReturnsView.as_view(), name="make_book_return"),
    path("approve_book_return/<int:pk>", approve_book_return, name="approve_book_return"),
    path("reject_book_return/<int:pk>", reject_book_return, name="reject_book_return"),

    path("library_report/", ReportView.as_view(), name="library_report"),
    path("book_stock_report_csv/", book_stock_report_csv, name="book_stock_csv"),
    path("popular_books_csv/", popular_books_csv, name="popular_books_csv"),
    path("high_paying_customers_csv/", high_paying_customers_csv, name="high_paying_customers_csv"),


    path("import_books_via_api/", ImportDataViaApiView.as_view(), name="import_data"),
    path("suspend_member/<str:username>/", suspend_unsuspend_member, name="suspend_unsuspend_member"),
    path("send_warning_message/<int:id>/", send_warning_message, name="send_warning_message"),

    path("reject_renewal_request/<int:pk>", RejectRenewalRequestView.as_view(), name="reject_renewal"),
    path("accept_renewal_request/<int:pk>", AcceptRenewalRequestView.as_view(), name="accept_renewal"),

    path("403/", test_, name='test'),

    path("high_paying_customers_pdf/", high_paying_customer_pdf, name="high_paying_customers_pdf"),
    path("popular_books_pdf/", popular_books_pdf, name="popular_books_pdf"),
    path("member_page/", MembersActionView.as_view(), name="member_page")

]

LMS/templates/base_generic.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width>, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link href="http://fonts.cdnfonts.com/css/the-jacklyn" rel="stylesheet">
<!--    <link href="http://fonts.cdnfonts.com/css/sora" rel="stylesheet">-->
<!--    <link href="http://fonts.cdnfonts.com/css/mulish" rel="stylesheet">-->
    <link href="http://fonts.cdnfonts.com/css/inter" rel="stylesheet">
<!--    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">-->
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>


<!--    <link rel="stylesheet" type="text/css" href="{% static 'styles/main.css' %}">-->
    {% block title %}
    <title>Title</title>
    {% endblock %}
</head>
<body>

<style>
    .messages li{
        list-style-type: none;
        z-index:1000
        position:relative;
        top:0;
        padding:5px;
        margin-top:-16px;
        font-size:13px;
        font-family:sora;
        color:white;
    }

    .messages--error{
        background-color:red;
    }

    .messages--success{
        background-color:green;

    }

    .messages--info{
        background-color:blue;
    }
</style>

<!--{% if messages %}-->
<!--<ul>-->
<!--    {% for message in messages %}-->
<!--    <li-->
<!--     {% if messages.tags == "error" %}-->
<!--            class="messages&#45;&#45;error"-->
<!--        {% elif messages.tags == "success" %}-->
<!--            class="messages&#45;&#45;success"-->
<!--        {% elif messages.tags == "info" %}-->
<!--            class="messages&#45;&#45;info"-->
<!--        {% endif %}>-->
<!--    {{message}}</li>-->
<!--    {% endfor %}-->
<!--</ul>-->
<!--{% endif %}-->



{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags == 'error' %}
        class="messages--error"
        {% elif message.tags == 'success' %}
        class="messages--success"
        {% elif message.tags == 'info' %}
        class="messages--info"

        {% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}



{% block content %}
{% endblock %}

</body>
</html>

LMS/templates/book_properties_page.html
{% extends "base_generic.html" %}
{% load static %}


{% block content %}
<style>

    .book--header{
        display:grid;
        grid-template-columns:0.5fr 3fr;

    }

    .book_tab li{
        list-style-type:none;
        display:inline;
        margin-right:40px;
        padding:5px;
    }

    .book_tab li:hover{
       cursor:pointer;
       color:#2E5185;
    }

    .book--properties h3{
        font-family: Mulish;
        font-size: 25px;
        font-weight: 400;
        line-height: 29px;
        text-align: left;
    }

    .book--container{
        border-top:70px solid #F9FAFB;
        border-bottom:65px solid #F9FAFB;
        border-left:25px solid #F9FAFB;
        border-right:25px solid #F9FAFB;
        border-radius:8px;
        height:1550px;
  }

   .book--container li{
        list-style-type:none;

   }

    .book_tab{
        margin-top:-60px;
    }

    #book_request,
    #unpicked_books,
    #books_returned,
    #renewal_request,
    #my_unpicked_books,
    #my_borrowed_books,
    #my_default_books{
        display:none;
    }



    #book_request{
       margin-top:100px;
       display:block;
    }

    #my_default_books,
    #my_borrowed_books,
    #my_unpicked_books,
    #renewal_request,
    #books_returned,
    #unpicked_books{
         margin-top:100px;
    }

    #my_default_books li,
   #my_borrowed_books li,
   #my_unpicked_books li,
   #renewal_request li,
   #books_returned li,
   #unpicked_books li,
   #book_request li{
       padding:10px;
       margin-left:30px
       margin-right:30px;
       width:1100px;
   }


    #my_default_books li:nth-child(odd),
   #my_borrowed_books li:nth-child(odd),
   #my_unpicked_books li:nth-child(odd),
   #renewal_request li:nth-child(odd),
   #books_returned li:nth-child(odd),
   #unpicked_books li:nth-child(odd),
   #book_request li:nth-child(odd){
      background-color:#F5F3F3;
    }


   #my_default_books p,
   #my_borrowed_books p,
   #my_unpicked_books p,
   #renewal_request p,
   #books_returned p,
   #unpicked_books p,
   #book_request p{
    font-family: Mulish;
    font-size: 15px;
    font-weight: 400;
    line-height: 15px;
    letter-spacing: 3px;
    text-align: left;
   }

   #my_default_books button,
   #renewal_request button,
   #books_returned button,
   #unpicked_books button,
   #book_request button{
    margin-left:80px;
    width:89px;
    height:35px;
    border-radius:8px;
    color:white;
   }

    .m_b_r,
    .approve_rr,
    .approve_br,
    .picked_ub,
    .accept_bq{
        border:1px solid #09C105;
        background-color:#09C105;

   }

    .a_p_r,
    .reject_rr,
    .reject_br,
    .delete_ub,
    .reject_bq{
        border:1px solid #AB0520;
        background-color:#AB0520;

   }

   .a_p_r:hover,
   .m_b_r:hover,
   .approve_rr:hover,
   .reject_rr:hover,
   .approve_br:hover,
   .reject_br:hover,
   .picked_ub:hover,
   .delete_ub:hover,
   .reject_bq:hover,
   .accept_bq:hover{
        cursor:pointer
   }

    .buttons{
        float:right;
        margin-top:-38px;
        margin-right:60px;
   }

   .a_p_r,
   .m_b_r{
    width:150px;
    margin-left:60px;
    height:35px;
    border-radius:8px;
    color:white;
   }

</style>
<div class="book--header">

        {% include "genre_component.html" %}

        <div class="book--properties">
            {% include "navbar.html" %}
            <h3>Books</h3>

            <div class="book--container">

                    <div class="book_tab">
                          <ul>
                              {% if request.user.is_staff %}
                                  <li class="book_tablinks" onclick="openCity(event, 'book_request')">Book Request</li>
                                  <li class="book_tablinks" onclick="openCity(event, 'unpicked_books')">Unpicked Books</li>
                                  <li class="book_tablinks" onclick="openCity(event, 'books_returned')">Books Returned</li>
                                  <li class="book_tablinks" onclick="openCity(event, 'renewal_request')">Renewal Request</li>
                              {% endif %}
                              <li class="book_tablinks" onclick="openCity(event, 'my_unpicked_books')">My Unpicked Books</li>
                              <li class="book_tablinks" onclick="openCity(event, 'my_borrowed_books')">My Borrowed Books</li>
                              <li class="book_tablinks" onclick="openCity(event, 'my_default_books')">My Default Books</li>
                          </ul>
                    </div>


                {% if request.user.is_staff %}
                    <div id="book_request" class="first-tab tabcontent">
                        <ul>
                            {% for book_request in book_requests %}
                            <li>
                                <p>{{forloop.counter}}. <strong>{{book_request.name.username | title}}</strong> wants to lend <em>{{book_request.book |truncatechars:22}}</em>{{book_request.date_requested}}</p>
                                <div class="buttons">
                                <a href="{% url 'management_system:accept_book_request' book_request.id %}" ><button class="accept_bq">Accept</button></a>
                                <a href="{% url 'management_system:reject_book_request' book_request.id %}" ><button class="reject_bq">Reject</button></a>
                                </div>
                            </li>
                            {% empty %}
                            <li>No Requests at the moment</li>
                            {% endfor %}
                        </ul>

                    </div>


                     <div id="unpicked_books" class="first-tab tabcontent">
                            <ul>
                            {% for unpicked_book in unpicked_books %}
                            <li>
                                <p>{{forloop.counter}}.  <em>{{unpicked_book.book |truncatechars:22}}</em> to be picked by <strong>{{unpicked_book.borrower.username | title}}</strong>{{unpicked_book.date_requested}}</p>
                                <div class="buttons">
                                <a href="{% url 'management_system:pick_unpicked_books' unpicked_book.id %}" ><button class="picked_ub">Picked</button></a>
                                <a href="{% url 'management_system:delete_unpicked_books' unpicked_book.id %}" ><button class="delete_ub">Delete</button></a>
                                </div>
                            </li>
                            {% empty %}
                            <li>No Unpicked Book at the moment</li>
                            {% endfor %}
                        </ul>

                    </div>



                    <div id="books_returned" class="first-tab tabcontent">
                             <ul>
                            {% for book_return in book_returns %}
                            <li>
                                <p>{{forloop.counter}}. <strong>{{book_return.borrowed_book.borrower.username | title}}</strong> wants to return <em>{{book_return.borrowed_book.book  |truncatechars:22}}</em></p>
                                <div class="buttons">
                                <a href="{% url 'management_system:approve_book_return' book_return.id %}" ><button class="approve_br">Approve</button></a>
                                <a href="{% url 'management_system:reject_book_return' book_return.id %}}" ><button class="reject_br">Reject</button></a>
                                </div>
                            </li>
                            {% empty %}
                            <li>No Books Returned at the moment</li>
                            {% endfor %}
                        </ul>
                    </div>


                    <div id="renewal_request" class="first-tab tabcontent">
                             <ul>
                            {% for renewal_request in renewal_requests %}
                            <li>
                                <p>{{forloop.counter}}. <strong>{{renewal_request.borrowed_book.borrower.username | title}}</strong> wants to renew <em>{{renewal_request.borrowed_book.book  |truncatechars:22}}</em> to be returned on {{renewal_request.new_date_of_return }}</p>
                                <div class="buttons">
                                <a href="{% url 'management_system:accept_renewal' renewal_request.id %}"><button class="approve_rr">Approve</button></a>
                                <a href="{% url 'management_system:reject_renewal' renewal_request.id %}"><button class="reject_rr">Reject</button></a>
                                </div>
                            </li>
                            {% empty %}
                            <li>No Renewal Request at the moment</li>
                            {% endfor %}
                             </ul>
                    </div>
                {% endif %}


                    <div id="my_unpicked_books" class="first-tab tabcontent">
                           <ul>
                            {% for unpicked_book in user_unpicked_books %}
                            <li>
                                <p>{{forloop.counter}}. You are yet to pick  <em>{{unpicked_book.book |truncatechars:22}}</em> from the Library, since {{unpicked_book.date_borrowed | timesince}} ago</p>
                            </li>
                            {% empty %}
                            <li>No Unpicked Book at the moment</li>
                            {% endfor %}
                           </ul>
                    </div>


                    <div id="my_borrowed_books" class="first-tab tabcontent">
                           <ul>
                            {% for borrowed_book in borrowed_books %}
                            <li>
                                <p>{{forloop.counter}}.  <em>{{borrowed_book.book |truncatechars:31}}</em> ,  {{borrowed_book.date_borrowed | timesince}} ago</p>
                                <div class="buttons">
                                <a href="{% url 'management_system:make_book_return' borrowed_book.id %}"><button class="m_b_r">Make Book Return</button></a>
                                <a href="{% url 'accounts:make_renewal' borrowed_book.id %}"><button class="a_p_r">Apply For Renewal</button></a>
                                </div>
                            </li>
                            {% empty %}
                            <li>No Borrowed Book at the moment</li>
                            {% endfor %}
                           </ul>
                    </div>


                    <div id="my_default_books" class="first-tab tabcontent">

                         <ul>
                            {% for default_book in default_books %}
                            <li>
                                <p>{{forloop.counter}}.  <em>{{default_book.book |truncatechars:31}}</em> was due  {{default_book.date_to_be_returned | timesince}} ago, and you will be charged Rs. 5 per day</p>
                                <div class="buttons">
                                <a href="{% url 'management_system:make_book_return' default_book.id %}"><button class="m_b_r">Make Book Return</button></a>
                                </div>
                            </li>
                            {% empty %}
                            <li>No Default Book at the moment</li>
                            {% endfor %}
                           </ul>

                    </div>


            </div>
            {% include 'footer.html' %}

        </div>


</div>



<script>
console.log("running.....")
    function openCity(evt, cityName) {
      var i, tabcontent, tablinks
      tabcontent = document.getElementsByClassName('tabcontent')
      for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = 'none'
      }
      tablinks = document.getElementsByClassName('tablinks')
      for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(' active', '')
      }
      document.getElementById(cityName).style.display = 'block'
      evt.currentTarget.className += 'active'
    }
  </script>
<script>
     document.querySelector(".a_p_r").addEventListener("click", function(){

        document.querySelector(".renewal--form").classList.add("active");

    });


    document.querySelector(".a_p_r").addEventListener("click", function(){

        document.querySelector(".renewal--form").classList.remove("active");

    });
</script>
{% endblock %}

LMS/templates/delete.html
{% extends "base_generic.html" %}


{% block content %}
<style>

</style>


<form action="{% url 'management_system:delete_book' book.bookID %}" method="POST">
    {% csrf_token %}

    <h3>Are You Sure You want to delete '{{book}}' ? </h3>


    <input type="submit" value="Confirm">
    <br>
    <input type="submit" value="Go back">



</form>

{% endblock %}

LMS/templates/footer.html
{% load static %}

<style>

    .footer{
        margin:0px 0px;

    }


    .footer li{
        list-style-type:none;
        float:right;
        display:inline;
        margin:0px 20px 0px 20px;
    }

    .footer p{
        float:left;
        font-family: Sora;
        font-size: 15px;
        font-weight: 400;
        line-height: 30px;
        text-align: left;
    }

    .footer img{
        height: 22px;
        width: 22px;
    }


    .footer a{
        cursor:pointer;
    }


</style>


<div class="footer">
    <p>Copyright © 2022 Vilgax Library - All Rights Reserved</p>

    <ul>
        <a><li><img src="{% static 'images/Frame-1.png' %}" alt="LinkedIn"></li></a>
        <a><li><img src="{% static 'images/Frame-2.png' %}" alt="Facebook"></li></a>
        <a><li><img src="{% static 'images/Frame-3.png' %}" alt="Instagram"></li></a>
        <a><li><img src="{% static 'images/Frame-4.png' %}" alt="YouTube"></li></a>
        <a><li><img src="{% static 'images/img_3.png' %}" alt="Twitter"></li></a>
    </ul>

</div>

LMS/templates/genre_component.html
{% load static %}

<style>

  .genre--grid h3{
    font-family: Sora;
    font-size: 19px;
    font-weight: 400;
    line-height: 29px;
    letter-spacing: 1px;
    text-align: left;
    margin-top:55px;


  }

  .genre--grid li{
    list-style-type:none;
    margin-left:-10px;

  }


  .genre--grid a{
    text-decoration:none;
    color:#54565B;
  }



  .genre--grid a:visited{
    text-decoration:none;
    color:#54565B;
  }


  .genre--icon{
    height: 16px;
    width: 16px;
    margin:0px 0px -20px -35px;
  }

  .home--profile--section{
      position:fixed;
      bottom:1px;
      margin-left:5px;

   }

   .home--profile--section img{
      height:80px;
      width:80px;
      border-radius: 50%;
      margin-bottom:-10px;



   }

   .home--profile--section h4{
      font-family: Sora;
      font-size: 18px;
      font-weight: 700;
      line-height: 29px;
      text-align: left;
      height: 11px;
      width: 123.697265625px;
   }

   .home--profile--section p{
      font-family: Sora;
      font-size: 14px;
      font-weight: 400;
      line-height: 14px;
      text-align: left;
      color:#8B908B;

   }

    .home--profile--section button{
      height: 40px;
      width: 190px;
      border-radius: 10px;
      padding: 16px 50px 16px 50px;
      background-color:#2A639C;
      border: 1px solid #2A639C;
      cursor:pointer;
   }


   .home--profile--section span{
      color:white;
      padding-bottom:9px;
   }



</style>


<div class="genre--grid">
    <h3>GENRE</h3>
    <ul>
      {% if genres %}
      <a href="{% url 'management_system:home' %}">
        <img src="{% static 'images/img.png'%}" alt="all" class="genre--icon">
        <li>All Books</li>
      </a>
      {% endif %}

      {% for genre in genres %}
      <div class="ind_genre">
        <a href="{% url 'management_system:home' %}?search={{genre}}">
          <img src="{% static 'images/img.png'%}" alt="{{genre}}" class="genre--icon">
          <li>{{genre}}</li>
        </a>
      </div>
      {% empty %}
      <li>No Genre At The Moment</li>
      {% endfor %}
    </ul>

      <div>

      <br>
      <br>

<!--        <a href="{% url 'management_system:test' %}">test</a>-->

      </div>


    <div class="home--profile--section">
        {% if request.user.is_authenticated %}
          <div class="profile">
            <img src="{{member.profile_picture.url}}" alt="{{request.user.username}}">
            <h4>{{request.user.username | title}}</h4>

            {% if not request.user.is_staff %}
            <p>Reader</p>
            {% else %}
            <p>Librarian</p>
            {% endif %}

            <a href="{% url 'accounts:profile_page'%}"><button type="submit"><span>View Profile</span></button></a>


          </div>
        {% else %}
          <a href="#"><button type="submit"><span>Sign In</span></button></a>
        {% endif %}



      </div>





  </div>

LMS/templates/navbar.html
{% load static %}

<style>
    .nav--bar{
        background-color:white;
        margin: 15px 0px 15px 15px;
    }

    .nav--logo{
        height: 62px;
        width: 80x;
        top: 78.18408203125px;
    }

    .nav--bar a {
        text-decoration:none;
        color:black;
        font-family: Sora;
        font-size: 14px;
        font-weight: 400;
        line-height: 18px;
        letter-spacing: 0em;
        text-align: left;

    }

    .nav--bar ul{
        float:right;
        background-color:yelllow;
    }

    .nav--bar li {
        list-style-type:none;
        color:black;
        display:inline;
        margin-right: 80px
    }

    .nav--bar li:hover{
        cursor:pointer;
     }

    #navbar-first-child li{
        color:#2A639C;
        font-family: Sora;
        font-size: 14px;
        font-weight: 800;
        line-height: 18px;
        letter-spacing: 0em;
        text-align: left;

    }

    .authenticated-navbar-last-child{
        height: 250px;
        width: 49px;
        background-color: #2A639C;
        border-radius:5px;
        padding: 16px;
    }

    .authenticated-navbar-last-child span{
        font-family: Inter;
        font-size: 14px;
        font-weight: 500;
        line-height: 17px;
        text-align: left;
        color:white;
    }


     .unauthenticated-navbar-last-child{
        height: 250px;
        width: 49px;
        background-color: #AB0520;
        border-radius:5px;
        padding: 16px;
    }

    .unauthenticated-navbar-last-child span{
        font-family: Inter;
        font-size: 14px;
        font-weight: 500;
        line-height: 17px;
        text-align: left;
        color:white;
    }


</style>


<div class="nav--bar">

    <img src="{% static 'images/v logo black.png'%}" alt="Vilgax Library" class="nav--logo" >

    <ul>
       <a href="{% url 'management_system:home' %}" id="navbar-first-child"> <li >Home</li></a>
        {% if not request.user.is_authenticated %}

            <a href="{% url 'accounts:sign_in' %}"><li class="authenticated-navbar-last-child" ><span>Sign In</span></li></a>
        {% else %}
            {% if request.user.is_staff %}
                <a href="{% url 'management_system:member_page' %}"><li>Members</li></a>
                <a href="{% url 'management_system:library_report' %}"><li>Report</li></a>
                <a  href="{% url 'management_system:import_data' %}" id="import_api_data_nav"><li>Import</li></a>
            {% endif %}
            <a href="{% url 'accounts:books' %}"><li>Books</li></a>
            <a href="{% url 'accounts:sign_out' %}"><li class="unauthenticated-navbar-last-child" ><span>Sign out</span></li></a>
        {% endif %}


    </ul>



</div>